//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonUtil.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonUtil.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///   每个 key 由 &apos;/&apos; 分隔
        ///   key 尾部加上 &apos;[*]&apos; 或 &apos;[数字]&apos; 表示数组元素
        ///   [*] 表示提取所有子元素
        ///   [数字] 表示提取第几个子元素，下标从 0 开始
        ///   根元素为数组时 key 为空，即 &apos;[*]&apos;
        ///*/
        ///
        ///{
        ///  &quot;checksum&quot;: &quot;b2b64d8731508dfdb1947374f8d84c84&quot;,
        ///  &quot;roots&quot;: {
        ///    &quot;bookmark_bar&quot;: {
        ///      &quot;children&quot;: [{
        ///        &quot;date_added&quot;: &quot;13231990026000000&quot;,
        ///        &quot;date_last_used&quot;: &quot;0&quot;,
        ///        &quot;guid&quot;: &quot;23032ff0-d950-4f2b-9506-120ee2ea9553&quot;,
        ///        &quot;id&quot;: &quot;2958&quot;,
        ///        &quot;name&quot;: &quot;163网易免费邮--中文邮箱第一品牌&quot;,
        ///        &quot;show_icon&quot;: false,
        ///        &quot;source&quot;: &quot;sync&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonExtractorViewDemoJson {
            get {
                return ResourceManager.GetString("JsonExtractorViewDemoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roots/bookmark_bar/children[*]/id
        ///roots/bookmark_bar/children[*]/url.
        /// </summary>
        internal static string JsonExtractorViewDemoPattern {
            get {
                return ResourceManager.GetString("JsonExtractorViewDemoPattern", resourceCulture);
            }
        }
    }
}
