//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonUtil.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonUtil.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ascii {
            get {
                object obj = ResourceManager.GetObject("Ascii", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CommonRegex {
            get {
                object obj = ResourceManager.GetObject("CommonRegex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阿保之功
        ///阿保之劳
        ///阿鼻地狱
        ///阿鼻叫唤
        ///阿党比周
        ///阿党相为
        ///阿庚逢迎
        ///阿狗阿猫
        ///阿姑阿翁
        ///阿家阿翁
        ///阿娇金屋
        ///阿匼取容
        ///阿剌吉酒
        ///阿郎杂碎
        ///阿猫阿狗
        ///阿弥陀佛
        ///阿绵花屎
        ///阿娜多姿
        ///阿耨达池
        ///阿耨达山
        ///阿耨多罗
        ///阿毗达磨
        ///阿毗地狱
        ///阿平绝倒
        ///阿其所好
        ///阿时趋俗
        ///阿世盗名
        ///阿世媚俗
        ///阿世取容
        ///阿顺取容
        ///阿私所好
        ///阿魏无真
        ///阿意苟合
        ///阿意取容
        ///阿意顺旨
        ///阿谀谄媚
        ///阿谀承迎
        ///阿谀逢迎
        ///阿谀奉承
        ///阿谀奉迎
        ///阿谀苟合
        ///阿谀求容
        ///阿谀曲从
        ///阿谀取容
        ///阿谀顺情
        ///阿谀顺意
        ///阿谀顺旨
        ///阿旨顺情
        ///阿尊事贵
        ///哀哀父母
        ///哀哀欲绝
        ///哀兵必胜
        ///哀而不伤
        ///哀感天地
        ///哀感顽艳
        ///哀感中年
        ///哀告宾服
        ///哀鸿遍地
        ///哀鸿遍野
        ///哀鸿满路
        ///哀毁骨立
        ///哀毁瘠立
        ///哀矜惩创
        ///哀矜勿喜
        ///哀乐相生
        ///哀乐中节
        ///哀梨并剪
        ///哀梨蒸食
        ///哀莫大于心死
        ///哀戚之情
        ///哀其不幸
        ///哀穷悼屈
        ///哀声叹气
        ///哀丝豪肉
        ///哀丝豪竹
        ///哀思如潮
        ///哀死事生
        ///哀天叫地
        ///哀恸顽艳
        ///哀痛欲绝
        ///哀喜交并
        ///唉声叹气
        ///挨挨擦擦
        ///挨挨挤挤
        ///挨挨抢抢
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idioms {
            get {
                return ResourceManager.GetString("Idioms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///   每个 key 由 &apos;/&apos; 分隔
        ///   key 尾部加上 &apos;[*]&apos; 或 &apos;[数字]&apos; 表示数组元素
        ///   [*] 表示提取所有子元素
        ///   [数字] 表示提取第几个子元素，下标从 0 开始
        ///   根元素为数组时 key 为空，即 &apos;[*]&apos;
        ///*/
        ///
        ///{
        ///  &quot;checksum&quot;: &quot;b2b64d8731508dfdb1947374f8d84c84&quot;,
        ///  &quot;roots&quot;: {
        ///    &quot;bookmark_bar&quot;: {
        ///      &quot;children&quot;: [{
        ///        &quot;date_added&quot;: &quot;13231990026000000&quot;,
        ///        &quot;date_last_used&quot;: &quot;0&quot;,
        ///        &quot;guid&quot;: &quot;23032ff0-d950-4f2b-9506-120ee2ea9553&quot;,
        ///        &quot;id&quot;: &quot;2958&quot;,
        ///        &quot;name&quot;: &quot;163网易免费邮--中文邮箱第一品牌&quot;,
        ///        &quot;show_icon&quot;: false,
        ///        &quot;source&quot;: &quot;sync&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonExtractorViewDemoJson {
            get {
                return ResourceManager.GetString("JsonExtractorViewDemoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roots/bookmark_bar/children[*]/url.
        /// </summary>
        internal static string JsonExtractorViewDemoPattern {
            get {
                return ResourceManager.GetString("JsonExtractorViewDemoPattern", resourceCulture);
            }
        }
    }
}
